version: '3.1'
 
services:
    nginx-proxy:
        image: nmreg.azurecr.io/nginx
        ports:
            - 80:80
        restart: always
        depends_on:
            - api
    api:
        image: nmreg.azurecr.io/minimalisticfileserver
        restart: always
        volumes:
            - /home/nmaurer:/publishedfiles
        expose:
            - "5000"

